name: Release


on:
  workflow_run:
    workflows: ["godot-ci export"]
    types:
      - completed
      
jobs:
   release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: false
          title: "Automatic Build"
          files: |
            build/windows
            build/linux
            build/mac
